### ISSUE TITLE
Unread counter never gets updated to a smaller number if blinking is off

### ISSUE THREAD

**Issue by Xiyng** [gyunaev/birdtray#369] opened 2020-05-20 19:25 UTC
**OS**: Windows 10 64-bit, possibly a fairly recent version of Linux Mint as well
**Birdtray version**: 1.8.1
**Thunderbird version**: 68.8.0 (32-bit)
**Birdtray origin**: Installer
**Qt version**: _NA_

**Description**
If _Blinking speed_ is set to _Off_, the unread counter on the icon never gets updated to a smaller number e.g. when reading emails.

**Expected behavior**
If _Blinking speed_ is set to _Off_, the unread counter on the icon never gets updated when the real number becomes either smaller or greater than shown on the icon.

**To Reproduce**
1. Receive an email.
2. Take a look at the unread counter on the icon.
3. Read the email received at step 1.
4. Take a look at the unread counter on the icon.

**Additional context**
Seems to be reproducible on Windows for sure. On Linux Mint, the number never seem to get smaller without restarting Birdtray, but I have not verified whether setting _Blinking speed_ to a value other than _Off_ actually makes it update. Of course I *suspect* it's the same as on Windows.

**Comment by Xiyng** [comment] 2020-05-20 19:27
Judging by a quick look at other issues, https://github.com/gyunaev/birdtray/issues/317 looks like it might have the same root cause.

**Comment by gyunaev** [comment] 2020-10-22 03:06
Please check with the latest release.

**Comment by Abestanis** [comment] 2022-11-15 08:02
I have just tested this on Windows and verified it in the code and I can confirm that the updating of the counter is independent of the *Blinking speed* setting.

It might have seen like the two are connected, because every time the settings are saved, he unread counter is updated.
Additionally, on Windows Birdtray is currently not really able to detect the changes immediately using the file watchers, because Thunderbird is not closing the mail account files after changing them, so the file watchers don't trigger. The most reliable way to see the updates to the unread counter on Windows currently is the force unread timer in the advanced settings tab.

If you find an instance, where you see in the log window that Birdtray parses a new unread counter, but doesn't update the tray icon, please reopen this issue or open a new one.

**Closed by Abestanis** 2022-11-15 08:02 UTC
Labels: bug
