### ISSUE TITLE
After the click Thunderbird doesn't restore to the previous visible state

### ISSUE THREAD

**Issue by qg0** [gyunaev/birdtray#378] opened 2020-06-05 22:09 UTC
Thunderbird 68.8.1
Birdtray 1.8.1 May 2 2020 09:53:28.
OpenSUSE Tumbleweed, Plasma KDE 5

Thuderbird is running and hidden. After the click on the Birdtray icon the Thunderbird doesn't restore to the previous visible state.
From the log:
```
2020-06-06 05:05:04 Warning: trying to hide already hidden window 
2020-06-06 05:05:04 Warning: trying to hide already hidden window 
2020-06-06 05:05:05 Warning: trying to hide already hidden window 
2020-06-06 05:05:05 Warning: trying to hide already hidden window 
```

**Comment by vedgy** [comment] 2020-08-25 16:18
Today I encountered this issue for the first time in Manjaro Xfce, Thunderbird 68.11.0. Built and installed *birdtray* git master version and the issue seems to be gone.

**Comment by vedgy** [comment] 2020-08-26 12:56
Today the issue happened again with the latest git master version. Restarting Birdtray and Thunderbird is a workaround.

Another one-shot workaround is to launch Thunderbird again, which activates the running but hidden instance. But then the bug remains, so clicking on the Birdtray icon won't restore Thunderbird visibility the next time.

**Comment by gyunaev** [comment] 2020-10-05 20:39
Duplicate of #370

**Closed by gyunaev** 2020-10-05 20:39 UTC
Labels: bug
