### ISSUE TITLE
Latest master branch doesn't open on Wayland until opened on X11

### ISSUE THREAD

**Issue by Handrail9** [gyunaev/birdtray#600] opened 2024-08-31 21:19 UTC
**OS**: Fedora 40 KDE Spin
**Linux Desktop Manager**:  KDE Plasma 6
**Birdtray version**:  Latest master branch (Commit #[ba14c17](https://github.com/gyunaev/birdtray/commit/ba14c17d87868aa165cb073c65c3df6801efe281))
**Thunderbird version**: 128.1.1esr Flatpak
**Birdtray origin**: Compiled from source
**Qt version**: QMake version 3.1
Using Qt version 6.7.2 in /usr/lib64

**Description**
When opening on Wayland birdtray fails to open. I opened it in a terminal but failed to record the error message that it gave. I can uninstall and reinstall if you think that error may be necessary. When switching to X11 and opening Birdtray opens fine, and then switching back to Wayland Birdtray will now open.

**Expected behavior**
Birdtray should open on it's own

**To Reproduce**
1. Install from source
2. Open on Wayland
3. Fails to launch
4. Switch to X11, repeat step 1
5. Switch to Wayland
6. Birdtray launches

**Comment by gyunaev** [comment] 2024-09-01 01:00
Duplicate of #426

**Closed** 2024-09-01 01:00 UTC
Labels: bug

**Comment by Handrail9** [comment] 2024-09-01 01:54
@gyunaev If this is a duplicate would it be possible to add the behavior to the problem description? I read that issue before opening this one and didn't feel that issue properly handled the one I filed for.

**Comment by gyunaev** [comment] 2024-09-01 01:56
I'm afraid I don't have nor use Wayland and thus have little interest in fixing Wayland-related issues.

**Comment by Handrail9** [comment] 2024-09-01 02:16
> I'm afraid I don't have nor use Wayland and thus have little interest in fixing Wayland-related issues.

Thats all fine and well, but if a contributer wanted to add Wayland support, proper documentation of Wayland-related issues would be needed.

**Comment by gyunaev** [comment] 2024-09-01 02:26
I guess "app doesn't work upon start" would be the first thing such a contributor would see personally :)

**Comment by Handrail9** [comment] 2024-09-01 02:32
So your solution to the problem, is not to leave it open, or even close it as "Not planned", but to close it as "Completed" implying that there was a solution provided and link a completely separate unrelated issue calling it a duplicate about Birdtray not being able to detect if Thunderbird is running due to a portal in Waylands protocol missing? It almost seems like you don't _want_ someone to contribute Wayland support if you're making your issues such a mess to comb through.

**Comment by gyunaev** [comment] 2024-09-01 02:35
This is not a bug. This software was never designed to run on Wayland, so the fact it does not is not an issue. Running on Wayland is a feature request. Someone who would want to implement it (to be clear, I don't care whether or not it will happen) could search for "wayland" and find issues - although an issue like "the app doesn't even start" does not really need any bug check.

**Comment by Handrail9** [comment] 2024-09-01 02:38
If this software is not designed to run on Wayland, and Wayland is not supported, include that in your README.md, and remove 
> Working with Wayland: at this moment Birdtray partially works with Wayland - email monitoring functionality works, but show/hide does not. Please track the issue https://github.com/gyunaev/birdtray/issues/426 to see the current status. Please do not report Wayland-related issues unless you built Birdtray from source yourself.

I see the app not starting on _Wayland_ as a _Wayland-related issue_.  It makes no sense to imply there is partial support when you do not want to support it in any capacity.

**Comment by Handrail9** [comment] 2024-09-01 02:44
https://github.com/gyunaev/birdtray/pull/601
