### ISSUE TITLE
Error retrieving accounts: Cannot query database - when Thunderbird is running

### ISSUE THREAD

**Issue by bxabi** [gyunaev/birdtray#121] opened 2019-09-16 11:51 UTC
**OS**: Arch Linux 5.2.14-arch2-1-ARCH #1 SMP PREEMPT x86_64 GNU/Linux
**Birdtray version**: Birdtray version 1.6.0 compiled at Sep 15 2019 11:12:08.
**Thunderbird version**: 68.1.0
**Birdtray origin**: from source
**Qt version**: 5.13.1
**Description**
I am using the global search database (because there I was getting correct counts, the mork files gave me 0)
Since a new Thunderbird release or a birdtray update (not sure which), the counts are only updating if I restart Thunderbird.
Also, if I go to the settings, I see the error message above if Thunderbird is running. If thunderbird is closed, there is no error message, and the counts are refreshed when I start it again.
So I think there is some kind of issue reading the database when Thunderbird is running.

**Expected behavior**
Counts refreshed, no error message when opening the settings.

**To Reproduce**

1. Start Thunderbird
2. Start Birdtray
3. Open the Settings (if you have accounts), or just try to add accounts.
4. see the error message

**Screenshots**
![image](https://user-images.githubusercontent.com/11303766/64955633-0b1bc800-d889-11e9-91ed-8b2fb70ccd7e.png)

**Comment by bxabi** [comment] 2019-09-20 09:52
I tested the 1.6 release from may, and it produces the same error, so it seems more likely that a thunderbird update created an incompatibility.

**Comment by stevenxxiu** [comment] 2019-09-28 01:50
I'm having a similar issue, also on Arch. My error is "Error updating database ... Cannot query database". The unread counter doesn't get updated properly due to this, and stays on 2 despite being 0, and cannot be cleared.

**Comment by bxabi** [comment] 2019-09-30 10:03
I started to debug this, and the problem is pretty clear. It seems Thunderbird keeps the sqlite database locked, which was apparently not the case in earlier versions. Or sqlite changed something?

But I get the same with the sqlite db browser, I can only open the database when thunderbird is closed.

I have no experience with sqlite, so not sure what can be done here, if there is a way to open the locked db.

**Comment by gyunaev** [comment] 2019-09-30 10:05
This means sqlite-based approach will no longer work with Thunderbird 68.

**Comment by bxabi** [comment] 2019-09-30 10:06
It seems so. I check then again if the mork file method works for me.

**Comment by gyunaev** [comment] 2019-09-30 10:10
By the way, can you access the sqlite database file by other means? I.e. can you for example run `hexdump` on it? Is it locked by the sqlite internal stuff, or by VFS?

**Comment by bxabi** [comment] 2019-09-30 10:24
yes, other means as hexdump work on it, so I think it is sqlite stuff.

**Comment by bxabi** [comment] 2019-09-30 10:29
If I select the inbox.msf with the mork file option, I'm getting 0 unread emails :(
Is that the right file?

Actually I get the same "Error retrieving accounts: Cannot query database" with the mork files too if Thunderbird is running. So the same issue stands for the other method as well :(

**Comment by gyunaev** [comment] 2019-09-30 10:36
Makes me wonder if this is specific to TH68, or to Arch? I'm not using TH68, so I can't test easily.

**Comment by bxabi** [comment] 2019-09-30 10:40
It was working well on Arch until a couple weeks ago, so I suppose it is Thunderbird, especially that the mork method is also affected when I enter the settings - but does update in the background, so maybe it will work if I reset the counter.
(sqlite version is 3.29.0)

**Comment by bxabi** [comment] 2019-09-30 10:53
By the way, just a note, in the code it seemed that the db is opened READ_WRITE, which is strange. I changed it to READ_ONLY but it didn't help with the locking.

**Comment by gyunaev** [comment] 2019-09-30 12:51
I can confirm that TB68 locks the search database, and thus accessing it is not possible without killing the TB process (which would be totally unpractical). Thus the sqlite-based parser is marked as only being supported for <68, and will be deprecated.

Please submit another issue regarding Mork parser.

**Closed by gyunaev** 2019-09-30 12:51 UTC
Labels: wontfix
