### ISSUE TITLE
Becomes out of sync/unreactive when Thunderbird was opened by notification

### ISSUE THREAD

**Issue by haarp** [gyunaev/birdtray#571] opened 2023-09-24 22:10 UTC
**OS**: Gentoo Linux
**Linux Desktop Manager**: Xfce (xfce4-notifyd-0.9.1, xfwm4-4.18.0)
**Birdtray version**: 1.11.4
**Thunderbird version**: 102.15.1
**Birdtray origin**: Ebuild
**Qt version**: _NA_

**Description**
When Thunderbird generates a new mail notifcation, it includes an "Activate" button. If the button is pressed, the Thunderbird is raised. In this state, Birdtray does not hide Thunderbird again when clicking on the tray icon. TB needs to be minimized manually first.

**Expected behavior**
Birdtray should always be able to control the TB window

**To Reproduce**
1. Enable new mail notifications
2. Press "Activate" in notification once new mail arrives
3. Try to hide TB again by clicking on the tray icon

Thanks a lot!

**Comment by BeatLink** [comment] 2023-11-19 12:36
Has there been any updates on this?

**Comment by gyunaev** [comment] 2023-11-21 01:27
No update since I don't use XFCE.  Anyone else using it is invited to troubleshoot what happens in WindowTools_X11::hide() and why it doesn't hide again.

**Comment by adatum** [comment] 2024-01-17 01:14
Same issue and workaround with Birdtray 1.11.4 on Fedora 39 and MATE 1.26.2.

**Comment by jboillot** [comment] 2024-01-26 16:07
Hello, I had the same issue with Birdtray 1.11.4 on Ubuntu 22.04 and GNOME 42.9.

After some testing, it appears that opening thunderbird via a new message notification does not trigger `WindowTools_X11::show`, so `mHiddenStateCounter` is not reset to `0`.
It implies that the condition of this `if` statement is `false` https://github.com/gyunaev/birdtray/blob/62e17bce9b777895ab7d23497351e2409aa37a34/src/windowtools_x11.cpp#L508

According to the few tests I did on my machine, the first term of the disjunction is sufficient and removing the `mHiddenStateCounter == 0` test corrects the issue.

However, I don't know if in the general case the second term can be ignored.

**Comment by haarp** [comment] 2024-01-30 00:12
@jboillot: Unfortunately can't confirm. I compiled Birdtray without the mHiddenStateCounter check and still couldn't get it to minimize to tray after activating via notification.

**Comment by tehw0lf** [comment] 2024-03-25 16:42
@jboillot can confirm, this solves the issue for me (Arch,Xfce 4.18.0,xfce4-notifyd-0.9.4, Birdtray 1.11.4 (self-compiled), TB 115.9.0)

I've opened a PR in case this is merge-worthy

**Comment by jboillot** [comment] 2024-03-25 17:01
I think this is not a #591 is not a satisfactory solution as, since I did the modification, every time I resume the session (lock-unlock), thunderbird is maximized.

**Comment by Paprikar** [comment] 2024-07-22 03:07
Prob duplicate of #550

**Closed** 2024-09-02 23:07 UTC
Labels: bug
