### ISSUE TITLE
Smart Mailboxes count not getting reset to zero 

### ISSUE THREAD

**Issue by RYRNRY** [gyunaev/birdtray#386] opened 2020-06-27 02:34 UTC
**Setup**
Birdtray version 1.8.1 compiled at Apr 29 2020 11:44:19.
Thunderbird 68.7.0 (32 bit)
Windows 7 Professional

**Issue**
Birdtray mailbox count does not get reset to ZERO once all the emails have been read. It stays at 2.  I have tried the 'Inbox - Repair Folder' option for all of my Inbox's with no success. This issue has persisted for more than a month now.

Also, I am not sure the association of SMART MAILBOXes to email accounts.

Let me know If I need to provide any log files.

![image](https://user-images.githubusercontent.com/32840664/85912704-26dad400-b7f4-11ea-9eeb-e0d497d632f0.png)

**Comment by Abestanis** [comment] 2020-10-03 23:14
Hi, sorry for not responding earlier. Do you still have this problem?
If so, could you please upload the problematic `Inbox.msf` file. You can use the script [here](https://github.com/gyunaev/birdtray/tree/master/contrib/anonymizeMork) to create a copy of that file without your personal data.

**Comment by Voczi** [comment] 2020-10-05 10:05
I have the same issue, this occurs every now and then so it's a bit hard to debug/reproduce. Also, a bit skeptic of uploading my "anonymized" .msf file. The read count does update in the end, but after about 5-10 minutes.
The Thunderbird window also shows up on log-on sometimes even if you set it to hide on tray when it starts and BirdTray's perceived status of Thunderbird bugs out whenever an automatic update for Thunderbird is initiated.

BirdTray has a bunch of weird quirks on Windows, but it used to work flawlessly on Ubuntu for me.

**Comment by Abestanis** [comment] 2020-10-05 10:35
@Voczi You don't need to upload your mork file. If the counter updates after a certain time, you most likely experience #95.
We added a workaround for that, you can enable the `Force index file re-read every X seconds` in the `Advanced` settings tab. Of course, this will add a bit of CPU load to your system because now Birdtray has to parse those mork files every `X` seconds.

The reason why Birdtray is not able to detect the changes is because of the way Thunderbird uses the mork files. They open them once at startup and never close them until Thunderbird exits. Unfortunately, the only way to [watch for file changes on Windows](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-readdirectorychangesw) without checking manually every so often does not report changes, until the file is closed (It is not even enough to flush the file).
I am searching for a better alternative, for example opening and closing the file ourselves will trigger an update check and reduce the CPU load, but I still have not found a solution that doesn't require active polling of the files.

**Comment by Voczi** [comment] 2020-10-05 10:40
> 
> 
> @Voczi You don't need to upload your mork file. If the counter updates after a certain time to the correct value, you most likely experience #95.
> We added a workaround for that, you can enable the `Force index file re-read every X seconds` in the `Advanced` settings tab. Of course, this will add a bit of CPU load to your system because now Birdtray has to parse those mork files every `X` seconds.
> 
> The reason why Birdtray is not able to detect the changes is because of the way Thunderbird uses the mork files. They open them once at startup and never close them until Thunderbird exits. Unfortunately, the only way to [watch for file changes on Windows](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-readdirectorychangesw) without checking manually every so often does not report changes, until the file is closed (It is not even enough to flush the file).
> I am searching for a better alternative, for example opening and closing the file ourselves will trigger an update check and reduce the CPU load, but I still have not found a solution that doesn't require active polling of the files.

Gotcha, thank you for the tip. I set it to update the index file periodically.

I will try to create separate issues for the rest of the bugs when I have spare time. Encountered another bug where pressing on a mail notification does not bring the window up. You would instead have to manually open Thunderbird by double-clicking on the Birdtray's tray icon and it would then, together with an attached Thunderbird window, also launch X amount of detached Thunderbird windows.

**Comment by Abestanis** [comment] 2020-10-05 10:51
> I will try to create separate issues for the rest of the bugs when I have spare time.

Please do so. We are planning to create a new release of Birdtray in 5 days, so if you have anything critical that should be fixed as soon as possible you might want to create an issue for it now rather than later. Otherwise it is probably going to be 3 to 4 months until the next release.

> You don't need to upload your mork file. If the counter updates after a certain time to the correct value, you most likely experience #95.

Just to clarify, @RYRNRY this does not apply to you. Your logs indicate that Birdtray re-parsed your mork file and still read a value of `2`. It looks like there might be something wrong with our Mork parser, which is why we need to have a look at the mork file.

Regarding the mork file, it contains the content of you emails for that specific account, so you don't want to upload the original mork file. We obviously don't need the contents of your mails to debug this problem, so please use the script I mentioned above. It *should* remove all of the mail contents, but you should always check before you upload. Luckily, mork files are just text files, so you can open them up in your favorite text editor and have a look at it.

**Closed** 2021-07-18 17:47 UTC
Labels: bug
