### ISSUE TITLE
Toggle not working sometimes

### ISSUE THREAD

**Issue by abenjak** [gyunaev/birdtray#370] opened 2020-05-22 09:42 UTC
**OS**: Linux Mint 19.1 Cinnamon
**Birdtray version**: 1.8.1
**Thunderbird version**: 68.8.0 (64-bit)
**Birdtray origin**: From installer
**Qt version**: _NA_ 

**Description**

Occasionally, Birdtray is not able to show the hidden Thunderbird window by using the tray icon's toggle feature (either by clicking on it if `Hide/show Thunderbird window when clicking on tray icon` option is checked, or by using the Birdtray's context menu).

The log just says:
`Warning: trying to hide already hidden window`

If this happens, trying to toggle from the terminal won't work either (but `-s` works, read below). It seems that for some reason Birdtray thinks the TB is shown while it is hidden, so the next toggle action would be to hide it, which won't work.
The other way around has never occurred, i.e. that the TB is shown and Birdtray cannot hide it.

**To Reproduce**
Well that's the problem, I have not yet figured out how to reproduce it. Tried to trigger the bug by minimizing from Thunderbird, or clicking on Birdtray icon quickly several times, to no avail. But it occurs to me almost every day. Sometimes it happens just after I hide the window after quickly clicking on the last unread message, but not sure this is the only scenario that can trigger this bug. Email monitoring seems to work during this "stuck" state.

**Fix**
"Forcing" to show the window with `birdtray -s` in the terminal solves the problem, and things get back to normal.

**Note (feature request)**
A workaround solution would be to add `Show Thunderbird` and `Hide Thunderbird` (corresponding to `-s` and `-H` respectively), somewhere in the context menu, maybe bury them under a new `Force show/hide` submenu or similar.

**Comment by yut23** [comment] 2020-08-01 22:49
It looks like this is caused by a race condition between `isHidden()` and `hide()` in `WindowTools_X11`:

1. Toggling calls `isHidden()`, which only returns true if `mHiddenStateCounter == 2`.
2. `hide()` calls `doHide()` twice, which increments `mHiddenStateCounter` each time.

If `isHidden()` runs in between the two `doHide()` calls (when the counter is 1), then the toggle code will think the window is shown and will try to hide the window again. This ends up incrementing the state counter past 2, so `isHidden()` will always return false and toggling won't work anymore. Running `show()` resets the counter to 0, solving the problem.

**Comment by Abestanis** [comment] 2020-10-03 22:50
@yut23 Thank you very much for the detailed analysis.
@gyunaev This is your area of expertise. Do you think we can fix this before the release? It doesn't sound to complicated.

**Comment by gyunaev** [comment] 2020-10-03 23:02
I've seen this also before, but was never able to reproduce it. @abenjak can you please try this patch?

**Comment by gyunaev** [comment] 2020-10-03 23:05
If you still have the issue, please provide the new log message (I now print the counter there)

**Comment by yut23** [comment] 2020-10-03 23:46
It should be `qMin`, not `qMax`. Currently, the counter jumps to 2 on the first call, then 3, 5, 7, etc.
Also, I was able to reproduce the race condition fairly reliably just by running something like `for i in {1..64}; do birdtray -t & done`, which tries to toggle 64 times in parallel.

**Comment by gyunaev** [comment] 2020-10-03 23:59
Thank you for the reproduction step. It was indeed a bit subtle. Should be fixed by now.

**Closed** 2020-10-04 16:52 UTC
Labels: bug
