### ISSUE TITLE
Not minimizing to tray after new window was opened

### ISSUE THREAD

**Issue by paulius-adamonis** [gyunaev/birdtray#93] opened 2019-06-05 18:06 UTC
Title is self explanatory. Birdtray does not minimize Thunderbird to tray when new Thunderbird window is launched. Steps to reproduce:
1.Open Birdtray with option to launch thunderbird with it on;
2.Hide Thunderbird to tray using Birdtray menu;
3.Launch Thunderbird from applications menu. At this point when minimizing new Thunderbird instance it does not hide to tray.

I'm running it on Ubuntu 19.04

**Comment by Abestanis** [comment] 2019-06-28 13:18
@gyunaev I think this is working as intended. Thunderbird is supposed to prevent multiple instances by itself. I also don't see the point of having two Thunderbird instances running simultaneously. So it's better not to hide a second instance so that the user will close it.

**Comment by paulius-adamonis** [comment] 2019-06-28 13:25
I totally agree with you, having multiple Thunderbird instances running at the same time is pointless so maybe Birdtray could launch the existing window instead of letting Thunderbird launch a new one?

**Comment by Abestanis** [comment] 2019-06-28 13:43
Well, the thing is, Thunderbird has a builtin mechanism that should prevent it from starting a second instance and a second window in the first place. Can you please provide your Thunderbird version and how you installed it, so we can reproduce?

**Comment by paulius-adamonis** [comment] 2019-06-29 10:01
I'm running Thunderbird 60.7.1 (64bit) and BirdTray 1.5. Thunderbird was preinstalled with Ubuntu and BirdTray was installed using "apt install birdtray" command. Ubuntu version is 19.04.

In BirdTray settings in "Hiding" tab I have checked these checkboxes:
"Start Thunderbird when Birdtray starts with a 0 second delay";
"and hide it";
Hide Thunderbird window when it is minimized".

Steps to reproduce the behaviour:
1.Open Birdtray. When trying to show and/or hide Thunderbird using Birdtray tray menu everything works as expected.
2.If Thinderbird window is open hide it using Birdtray menu and launch Thunderbird using applications launcher.
3.Hide Thunderbird and try to show it again using Birdtray menu. Now Thunderbird hides but doesn't show up again.

**Comment by gyunaev** [comment] 2019-09-04 22:31
> with a 0 second delay
this probably needs to be changed in your setup. Make it 5+.

**Closed** 2019-12-07 22:23 UTC
